config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  get 'welcome/index'

resources :notes 

resources :categories

   root 'welcome#index'
get "/about", :to => "welcome#about"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :notes, :dependent => :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
 has_ancestry
 belongs_to :category
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable,:confirmable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


 def is_login?
    unless current_user
      redirect_to root_path
   end
  end
  
   def layout?
    if current_user and current_user.role == 'admin'
      "admin"
    end
  end

 before_action :configure_permitted_parameters, if: :devise_controller?
  
    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:email,:role, :first_name, :last_name, :username, :gender_type_list, :name, :address, :city, :phone, :date_of_birth,:password, :student, :password_confirmation)
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)

      if current_user.role == 'user'
         root_path()
      elsif current_user.role == 'admin'
          
        home_index_path()
       else
         root_path()
      end
   end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	layout :layout?, only: [:index,:new,:destroy,:show,:create]

	def index
		@categories= Category.all
	@notes=Note.all
		@category= Category.new
	end
	
	def new
		@category= Category.new
	end
	def create
		@category= Category.new(category_params)
		 @category.save
			redirect_to categories_path
	end
	def show
		@category= Category.find(params[:id])
	end
	def edit
		@category= Category.find(params[:id])
	end
	def update
		@category= Category.find(params[:id])
		if @category.update(category_params)
			redirect_to categories_path
		else
			render 'edit'
		end
	end
	def destroy
		@category= Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end
	private
	def category_params
		params.require(:category).permit!
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   layout :layout?
	before_filter :is_login?

  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	
layout :layout?, only: [:index,:new,:destroy,:show, :create]

def index
@category = Category.find_by(:name=>params[:category].present? ? params[:category] : 'work')
@notes = Note.where(category_id: @category.id).order("created_at DESC")
@note= Note.new
end

def new
	@note= Note.new(:parent_id => params[:parent_id])

	@notes=Note.all
	end

def create
	@note= Note.new(note_params)
	if @note.save
		redirect_to notes_path
	else
		render"new"
	end
end

def show
	@note= Note.find(params[:id])
end

def edit
@note= Note.find(params[:id])
end

def destroy
	@note= Note.find(params[:id])
	@note.destroy
	redirect_to notes_path
end

def update
	@note= Note.find(params[:id])
	if @note.update(note_params)
		redirect_to new_notes_path
	else
		render "edit"
	end
end

def note_params
	params.require(:note).permit!
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nested_notes(messages)
    messages.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_notes(sub_messages), :class => "nested_messages")
    end.join.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :parent_id %>
   <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> 
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
   <td><%= category.name %></td>
        
       <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    

<% end %>

</tr>
  </tbody>
</table>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> 
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">WelCome Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">26</div>
                                    <div>New Comments!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">12</div>
                                    <div>New Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">124</div>
                                    <div>New Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">13</div>
                                    <div>Support Tickets!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            

app/views/layouts/_footer.html.erb
		<footer class="footer-basic-centered">

			<p class="footer-company-motto"></p>

			<p class="footer-links">
				<a href="#">Home</a>|
				
				<a href="#">Blog</a>|
				
				<a href="#">Pricing</a>|
				
				<a href="#">About</a>|
				
				<a href="#">Faq</a>|
				
				<a href="#">Contact</a>
			</p>

			<p class="footer-company-name">s &copy; 2016</p>

		</footer>


<style>

.footer-basic-centered{
	background-color: #292c2f;
	box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
	box-sizing: border-box;
	width: 100%;
	text-align: center;
	font: normal 18px sans-serif;
	padding: 65px;
	margin-top: 80px;
}

.footer-basic-centered .footer-company-motto{
	color:  #8d9093;
	font-size: 24px;
	margin: 6px;
}

.footer-basic-centered .footer-company-name{
	color:  #8f9296;
	font-size: 14px;
	margin: 0;
}

.footer-basic-centered .footer-links{
	list-style: none;
	font-weight: bold;
	color:  #ffffff;
	padding: 35px 0 23px;
	margin: 0;
}

.footer-basic-centered .footer-links a{
	display:inline-block;
	text-decoration: none;
	color: inherit;
}

/* If you don't want the footer to be responsive, remove these media queries */

@media (max-width: 600px) {

	.footer-basic-centered{
		padding: 35px;
	}

	.footer-basic-centered .footer-company-motto{
		font-size: 18px;
	}

	.footer-basic-centered .footer-company-name{
		font-size: 12px;
	}

	.footer-basic-centered .footer-links{
		font-size: 14px;
		padding: 25px 0 20px;
	}

	.footer-basic-centered .footer-links a{
		line-height: 1.8;
	}
}
</style>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wpw</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav id ="nav">
 </div> 

<div id= "page_nav" >
<%= link_to "WPW", "#" %>

     </div>
                     
<div id= "sign_in" >
<%=link_to current_user.email,  "#"%>
  <%= link_to "<i class='fa fa-fw fa-power-off'></i>".html_safe, destroy_user_session_path, :method => 'delete' %>
<%#=link_to "Note",notes_path %>

</div>

</nav>

<div id= "main_wrap" >

 <div class="onlinesticker-container onlinesticker-border">

<div class="row">

  <div class="col-md-2"</div>
  <li>

  <li>
<h5><%=link_to "Dashboard",home_index_path,class: "btn btn-default" %></h5>
 <% Category.all.each do |category| %>
<h5><%= link_to category.name,  notes_path(:category => category.name),class: "btn #{category.name == 'work' ? 'btn-success' : category.name == 'play' ? 'btn-danger' : 'btn-primary'}"%></h5>
<% end %></li>

</div>
</li>

  <div class="row">

  <div class="col-md-9"</div>

<%= yield %>

</div>
</div>

 <div id="sticker_all"></div>

<div id= "footer" >


 
</footer>

</body>
</html>
</div>

<style>
body {
    margin: 2px;
       width:100%;
           height: 2%;
}
#nav {
    background: none repeat scroll 0 0 gray;
    float: right;
    height: 108px;
    width: 100%;
}

li {
    background-color: gray;
    height: 100%;
    list-style-type: none;
    margin: -66px;
    overflow: auto;
    padding: 44px;
    position: fixed;
}

li a {
    color: white;
    display: block;
    padding: 18px 5px 5px 25px;
    text-decoration: none;
}
h5 {
    background-color: gray;
    color: white;
    padding: -6 -7 14px;
}
h5, .h5 {
    font-size: 15px;
}
li :hover:not(.active) {
    color: white;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wpw" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>


  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Wpw</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path  %></li>
            <li><%#= link_to "Notes", new_note_path  %></li>
            <li><%= link_to "About", about_path  %></li>
          </ul>
           <ul class="nav navbar-nav navbar-right">
<% if current_user %>
<%=link_to current_user.email,  "#"%>
   <%= link_to image_tag("2.png", size: "20x20", alt: "Edit Entry"),  destroy_user_session_path, :method => :delete %>
  <% else %>
 
      <li><%= link_to "Signup", new_user_registration_path  %></li>
       <li><%= link_to "Signin", new_user_session_path  %></li>
  <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
     <!--    <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>/.well -->
        </div><!--/span-->
      </div><!--/row -->

    </div> <!-- /container -->
      <footer>
        <p><%#= render 'layouts/footer' %></p>

      </footer>


  </body>
</html>




<style>
.navbar-default {
    background-color:#40E0D0;
    border-color: #e7e7e7;
}
.navbar-brand {
    margin-left: -72px;
}
.navbar-nav > li > a {
    padding-bottom: 15px;
    padding-top: 35px;
}
.navbar-static-top {
    border-width: 0 0 1px;
    z-index: 1000;
}
.navbar {
    border: 1px solid transparent;
    margin-bottom: 1px;
    min-height: 80px;
    position: relative;
}
.navbar {
    border-radius: 4px;
}

</style>

app/views/notes/_form.html.erb
<%= form_for @note,:url => notes_path, :html => {:method => 'POST'}  do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :parent_id %>
  
<div class="form-group">
    <%= f.hidden_field :category_id, :value => @category.id %>
  </div>
   <%= f.label :Name %><br/>
  <div class="input-group">
          
          <%= f.text_field :name, placeholder: "name", class: "form-control input-lg", label: false, :required =>true %>
        </div><br/>

     <%= f.label :Subject %><br/>
  <div class="input-group">
          
          <%= f.text_field :subject, placeholder: "subject", class: "form-control input-lg", label: false, :required =>true %>
        </div><br/>
 
   <%= f.label :Description %><br/>
  <div class="input-group">
          
          <%= f.text_area :description, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
        </div><br/>
   
     <%= f.label :File %><br/>
  <div class="input-group">
          
          <%= f.file_field :attachment, placeholder: "", class: "form-control input-sm", label: false, :required =>true  %>
        </div><br/>
  <div class="actions">
    <%= f.submit "Create Notes",class: "btn btn-success" %>
  </div>

<% end %>

app/views/notes/_index.html.erb
    <div class="text-right">
<%#= nested_notes @notes.arrange(:order => :created_at) %>
</div>

<%= render "form" %>

<table class="table table-bordered table-striped">

  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Description</th>	
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.name %></td>
        <td><%= note.subject %></td>
        <td><%= note.description %></td>
        <td><%= link_to "Download note", note.attachment_url %></td>

        <td><%= button_to "Delete",  note, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{note.name}?" %>
        <%= note.created_at.strftime("%B %d, %Y ") %>
            </td>
      </tr>
    <% end %>

  </tbody>
</table>
<style>
   div.text-right{
     float: right;
}
</style>


 

app/views/notes/_note.html.erb
<div class="note">

  <div class="created_at"><%= note.created_at.strftime("%B %d, %Y ") %></div>
  <div class="name">
    Name:<%= link_to note.name, note %><br>
     
  </div>

</div>
<style>
   div.text-right{
     float: right;
}
</style>

app/views/notes/edit.html.erb
edit.html.erb

app/views/notes/index.html.erb
<%= render "index" %>

app/views/notes/new.html.erb
<%= render @note.parent if @note.parent %>

<%= render "form" %>

<p><%= link_to "Back to notes", notes_path %></p>

app/views/notes/show.html.erb
<%= nested_notes @note.subtree.arrange(:order => :created_at) %>

<p><%= link_to "Back to Notes", notes_path %></p>

app/views/welcome/about.html.erb
about.html.erb